host: '[spqr_router_1_1]'
router_port: '6432'
admin_console_port: '7432'
grpc_api_port: '7000'
init_sql: /spqr/docker/router/init.sql
router_mode: PROXY
log_level: debug
time_quantiles:
  - 0.8
frontend_tls:
  key_file: /etc/odyssey/ssl/server.key
  cert_file: /etc/odyssey/ssl/server.crt
  sslmode: disable
frontend_rules:
  - usr: gauss
    db: db1
    pool_default: true
    pool_mode: TRANSACTION
    pool_prepared_statement: false
    auth_rule:
      auth_method: ldap
      ldap_config:
        ldapserver: ldap.forumsys.com
        ldapport: 389
        ldapscheme: ldap
        ldapbasedn: dc=example,dc=com
        ldapbinddn: cn=read-only-admin,dc=example,dc=com
        ldapbindpasswd: password
world_shard_fallback: true
shards:
  sh1:
    tls:
      key_file: /etc/odyssey/ssl/server.key
      sslmode: disable
      cert_file: /etc/odyssey/ssl/server.crt
    db: db1
    usr: gauss
    pwd: 12345678
    type: DATA
    hosts:
      - 'spqr_shard_1:6432'
  sh2:
    tls:
      key_file: /etc/odyssey/ssl/server.key
      sslmode: disable
      cert_file: /etc/odyssey/ssl/server.crt
    db: db1
    usr: gauss
    pwd: 12345678
    type: DATA
    hosts:
      - 'spqr_shard_2:6432'
  w1:
    tls:
      key_file: /etc/odyssey/ssl/server.key
      sslmode: disable
      cert_file: /etc/odyssey/ssl/server.crt
    db: db1
    usr: gauss
    pwd: 12345678
    type: WORLD
    hosts:
      - 'spqr_world:6432'
backend_rules:
  - usr: gauss
    db: db1
    pool_discard: true
    pool_rollback: true
